include mingw headers on win32 (#101)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,6 +23,7 @@ jobs:
           echo "LD=clang++" >> $GITHUB_ENV
           echo "LLVM_VERSION=$(cat llvm/llvm.version)" >> $GITHUB_ENV
           echo "LLVM_COMMIT=$(cd llvm/llvm-project && git rev-parse --short HEAD)" >> $GITHUB_ENV
+          echo "STATIC_LLVM=1" >> $GITHUB_ENV
 
       - name: Cache LLVM
         id: cache-llvm
@@ -33,18 +34,18 @@ jobs:
           key: llvm-${{ runner.os }}-${{ env.LLVM_COMMIT }}
 
       - name: Set up llvm
-        run: make STATIC_LLVM=1 prepare-llvm
+        run: make prepare-llvm
 
       - name: Compile nim
-        run: make STATIC_LLVM=1 prepare-nim
+        run: make prepare-nim
 
       - name: Run tests
         run: |
           cat ci-skipped-tests.txt >>skipped-tests.txt
-          make STATIC_LLVM=1 test
+          make test
 
       - name: Run self-compare
-        run: make STATIC_LLVM=1 compare
+        run: make compare
 
       - name: Cross-compile
         run: |
@@ -102,7 +103,8 @@ jobs:
           echo "LD=clang++" >> $GITHUB_ENV
           echo "LLVM_VERSION=$(cat llvm/llvm.version)" >> $GITHUB_ENV
           echo "LLVM_COMMIT=$(cd llvm/llvm-project && git rev-parse --short HEAD)" >> $GITHUB_ENV
-          echo "PATH=$PATH:$PWD >> $GITHUB_ENV"
+          echo "PATH=$PATH:$PWD" >> $GITHUB_ENV
+          echo "STATIC_LLVM=1" >> $GITHUB_ENV
 
       - name: Cache Nim DLLs (Windows)
         if: runner.os == 'Windows'
@@ -136,20 +138,20 @@ jobs:
           key: llvm-${{ runner.os }}-${{ env.LLVM_COMMIT }}
 
       - name: Set up llvm
-        run: make STATIC_LLVM=1 prepare-llvm
+        run: make prepare-llvm
 
       - name: Compile nim
-        run: make STATIC_LLVM=1 prepare-nim
+        run: make prepare-nim
 
       - name: Run tests
         run: |
           cat ci-skipped-tests.txt >>skipped-tests-win.txt
-          make STATIC_LLVM=1 test || true # TODO enable hard fail on tests
+          make test || true # TODO enable hard fail on tests
 
       - name: Run self-compare
         # On windows, nlvm.self cannot raise exceptions, likely due to a conflict
         # with libunwind in libc++ - this needs further investigation
-        run: make STATIC_LLVM=1 compare || true
+        run: make compare || true
 
       - name: Create distribution
         run: bash make-dist-windows.sh
