Integrate clang via libclang for self-contained C/C++ compilation (#89)
Using `libclang`, integrate `clang` into the `nlvm` binary to provide:

* native handling of `{.compile.}`
* `nlvm cc` for compiling C code with the same infrastructure as `nlvm`
would normally use, including cross compilation (ie `nlvm --os:windows
cc myfile.`)

This patch is mostly about the infrastructure around clang - ie building
it, moving things around to make room for runtime libraries etc - in
particular, parallel compilation is still missing as is better
integration of runtime libraries (ie mingw).

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -13,7 +13,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y libcurl4-openssl-dev libsdl1.2-dev libgc-dev libncurses5-dev jq cmake ninja-build clang libfuse2 valgrind libncurses5 libzstd-dev
       - name: Check out repository code
-        uses: actions/checkout@v6
+        uses: actions/checkout@v7
         with:
           submodules: recursive
       - name: Set up environment
@@ -22,14 +22,15 @@ jobs:
           echo "CXX=clang++" >> $GITHUB_ENV
           echo "LD=clang++" >> $GITHUB_ENV
           echo "LLVM_VERSION=$(cat llvm/llvm.version)" >> $GITHUB_ENV
+          echo "LLVM_COMMIT=$(cd llvm/llvm-project && git rev-parse --short HEAD)" >> $GITHUB_ENV
 
       - name: Cache LLVM
         id: cache-llvm
-        uses: actions/cache@v5
+        uses: actions/cache@v6
         with:
           path: |
             llvm/sta
-          key: llvm-${{ runner.os }}-${{ env.LLVM_VERSION }}
+          key: llvm-${{ runner.os }}-${{ env.LLVM_COMMIT }}
 
       - name: Set up llvm
         run: make STATIC_LLVM=1 prepare-llvm
@@ -48,8 +49,8 @@ jobs:
       - name: Cross-compile
         run: |
           ./dl-llvm-mingw.sh
-          ./env.sh nlvm/nlvmr c --os:windows Nim/compiler/nim
-          [ -f Nim/compiler/nim.exe ] || { echo "nim.exe missing" ; exit 1 ; }
+          ./env.sh nlvm/nlvmr c --os:windows lib/nim/compiler/nim
+          [ -f lib/nim/compiler/nim.exe ] || { echo "nim.exe missing" ; exit 1 ; }
 
       - name: Create distribution
         run: bash make-dist-linux.sh
@@ -83,7 +84,7 @@ jobs:
             cmake:p
             ninja:p
             gcc:p
-      - uses: actions/checkout@v6
+      - uses: actions/checkout@v7
         with:
           submodules: recursive
 
@@ -94,11 +95,12 @@ jobs:
           echo "CXX=clang++" >> $GITHUB_ENV
           echo "LD=clang++" >> $GITHUB_ENV
           echo "LLVM_VERSION=$(cat llvm/llvm.version)" >> $GITHUB_ENV
+          echo "LLVM_COMMIT=$(cd llvm/llvm-project && git rev-parse --short HEAD)" >> $GITHUB_ENV
           echo "PATH=$PATH:$PWD/llvm-ming-20251216-ucrt-x86_64/bin >> $GITHUB_ENV"
 
       - name: Cache Nim DLLs (Windows)
         if: runner.os == 'Windows'
-        uses: actions/cache@v4
+        uses: actions/cache@v6
         id: cache-nim-dlls
         with:
           path: nim-dlls.zip
@@ -120,11 +122,11 @@ jobs:
 
       - name: Cache LLVM
         id: cache-llvm
-        uses: actions/cache@v5
+        uses: actions/cache@v6
         with:
           path: |
             llvm/sta
-          key: llvm-${{ runner.os }}-${{ env.LLVM_VERSION }}
+          key: llvm-${{ runner.os }}-${{ env.LLVM_COMMIT }}
 
       - name: Set up llvm
         run: make STATIC_LLVM=1 prepare-llvm
@@ -156,7 +158,7 @@ jobs:
   nph:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v6
+      - uses: actions/checkout@v7
       - name: Check `nph` formatting
         uses: arnetheduck/nph-action@v1
         with:
